LPS-116387 Add workflow support for account roles
drewbrokke/liferay-portal pull request #1185
Opened 2020-10-02 17:52 UTC by pei-jung

Hey Drew,

Can you review my changes for adding the workflow support for account roles? In order to fully support account roles in the workflow, it requires modification to the workflow definition schema. We won't be able to create the new schema file until 7.3 is released so we'll need to hold off on sending the changes. Yet, I'd like to get your review first to make sure the changes are good so we can send it as soon as 7.3 is released. Thanks\!

2020-10-02 17:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-10-02 17:54 UTC, pei-jung commented on definitions/liferay-workflow-definition_7_3_0.xsd
> +			<xs:enumeration value="account" />
This is temporary change. We'll need to create a new schema `liferay-workflow-definition_7_4_0.xsd` and apply the change.

2020-10-02 17:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/3183/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-source-format/builds/3183/jenkins-report.html">here</a>.</b></p>

2020-10-02 18:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ba97db5d9cac893f46425134b84295b1dbb1ad4">8ba97db5d9cac893f46425134b84295b1dbb1ad4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pei-jung/liferay-portal/tree/LPS-116387">LPS-116387</a><br/>Branch GIT ID: <a href="https://github.com/pei-jung/liferay-portal/commit/819e842d3fa626b5d8037af4fd02bce3948060e7">819e842d3fa626b5d8037af4fd02bce3948060e7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/3183/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/3183/jenkins-report.html">here</a>.</h5></details></html>

2020-10-02 18:03 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-13.liferay.com/job/test-portal-source-format/3183/">test-portal-source-format#3183</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/3183/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/drewbrokke/liferay-portal/pull/1185">drewbrokke#1185</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/46830.aspx">master - pei-jung > drewbrokke - PR#1185 - 2020-10-02[10:58:08]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/10479/">publish-spira-report#10479</a><br />

2020-10-02 22:51 UTC, drewbrokke requested changes
Hey Pei, overall this looks good to me. I only left one comment of something I think should change.

Are there any other places we can add test coverage for this feature? I'm not familiar with it so there may not be, but I figured I'd at least ask.

Overall, looks good!

2020-10-02 22:51 UTC, drewbrokke commented on modules/apps/roles/roles-admin-api/src/main/java/com/liferay/roles/admin/role/type/contributor/RoleTypeContributor.java
> +	}
Would it be reasonable to instead use `RoleConstants.getTypeLabel(getType())` as the default? If we did that, we wouldn't have to update any of implementations.

2020-10-09 19:32 UTC, drewbrokke commented
ci:test:relevant

2020-10-09 19:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/7788/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7788/jenkins-report.html">here</a>.</b></p>

2020-10-09 21:08 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 48 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f15ff4b951cd6a8e9ba6ee14391ef2da378eb2d">5f15ff4b951cd6a8e9ba6ee14391ef2da378eb2d</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/7788/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7788/jenkins-report.html">here</a>.</b></p>

2020-10-13 15:53 UTC, pei-jung commented
see https://github.com/pei-jung/liferay-portal/pull/711.

2020-10-13 15:53 UTC, closed without merging