LPS 199149 TECHNICAL TASK v0 remove manual env var injection review
drewbrokke/liferay-portal pull request #1527
Opened 2023-10-13 23:30 UTC by gamerson

- LPS-199149 liferay-clarity-etc-spring-boot: removes manual env var injection from build.gradle
- LPS-199149 liferay-jethr0-etc-spring-boot: removes manual env var injection from build.gradle
- LPS-199149 liferay-marketplace-etc-spring-boot: removes manual env var injection from build.gradle
- LPS-199149 liferay-partner-etc-cron: removes manual env var injection from build.gradle
- LPS-199149 liferay-ticket-etc-cron: removes manual env var injection from build.gradle
- LPS-199149 liferay-ticket-etc-spring-boot: removes manual env var injection from build.gradle
- LPS-199149 try to stabilize test with retry/wait

2023-10-13 23:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-13 23:31 UTC, gamerson commented
ci:test:liferay-sample-workspace

2023-10-13 23:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>liferay-sample-workspace</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/11494/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11494/jenkins-report.html">here</a>.</b></p>

2023-10-20 13:16 UTC, gamerson commented
ci:test:liferay-sample-workspace

2023-10-20 13:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>liferay-sample-workspace</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6780/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6780/jenkins-report.html">here</a>.</b></p>

2023-10-23 21:36 UTC, drewbrokke commented
ci:test:liferay-sample-workspace

2023-10-23 21:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>liferay-sample-workspace</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3971/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3971/jenkins-report.html">here</a>.</b></p>

2023-10-23 21:52 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:liferay-sample-workspace - 0 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eea775f659698232bec1fa5eb34ad634669ee4ba">eea775f659698232bec1fa5eb34ad634669ee4ba</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/635e1b80858aa3fa264af7df8926cd31445747ec">635e1b80858aa3fa264af7df8926cd31445747ec</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2445459545">EE Development Acceptance (master) - 101 - 2023-10-23[04:41:29]</a></p><details><summary><strong>ci:test:liferay-sample-workspace - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3971/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3971/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3971/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>POSHI Validation Failure<pre> [parallel] 2 errors in Poshi Script syntax
 [parallel] 
 [parallel] 1. Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/ClientExtensionsSamples.testcase:192
 [parallel]   185 |
 [parallel]   186 |            var springBootLogFile = "\$\{projectDir\}/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-cron/logs/spring.log";
 [parallel]   187 |
 [parallel]   188 |            var springBootLogFileContent = FileUtil.read(\$\{springBootLogFile\});
 [parallel]   189 |
 [parallel]   190 |            echo(\$\{springBootLogFileContent\});
 [parallel]   191 |
 [parallel] &gt; 192 |            var found = false;
 [parallel]   193 |            var trys = 5;
 [parallel]   194 |
 [parallel]   195 |            while (!(contains(\$\{springBootLogFileContent\}, "There are 0 message board threads in the Guest site")) &amp;&amp; !(MathUtil.isGreaterThan(\$\{trys\}, 0))) \{
 [parallel]   196 |                Pause(locator1 = 1000);
 [parallel]   197 |
 [parallel]   198 |                var trys = MathUtil.difference(\$\{trys\}, 1);
 [parallel]   199 |            \}
 [parallel] 
 [parallel] 
 [parallel] 2. Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/ClientExtensionsSamples.testcase:192
 [parallel]   185 |
 [parallel]   186 |            var springBootLogFile = "\$\{projectDir\}/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-cron/logs/spring.log";
 [parallel]   187 |
 [parallel]   188 |            var springBootLogFileContent = FileUtil.read(\$\{springBootLogFile\});
 [parallel]   189 |
 [parallel]   190 |            echo(\$\{springBootLogFileContent\});
 [parallel]   191 |
 [parallel] &gt; 192 |            var found = false;
 [parallel]   193 |            var trys = 5;
 [parallel]   194 |
 [parallel]   195 |            while (!(contains(\$\{springBootLogFileContent\}, "There are 0 message board threads in the Guest site")) &amp;&amp; !(MathUtil.isGreaterThan(\$\{trys\}, 0))) \{
 [parallel]   196 |                Pause(locator1 = 1000);
 [parallel]   197 |
 [parallel]   198 |                var trys = MathUtil.difference(\$\{trys\}, 1);
 [parallel]   199 |            \}
 [parallel] [functional-workspaces-bundle-mysql57-jdk8] Retry creating a test class group in 5 seconds.
 [parallel] ant -f build-test.xml prepare-poshi-runner-properties
 [parallel] Executing commands: git push --delete git@cloud-10-0-0-37:liferay/liferay-portal cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Deleted git@cloud-10-0-0-35:liferay/liferay-portal branches:
 [parallel]     cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git branch | grep [\s\*]*master\$
 [parallel] Executing commands: git rev-parse master
 [parallel] Buildfile: /opt/dev/projects/github/liferay-portal/build-test.xml
 [parallel] Executing commands: git rev-parse master
 [parallel] Executing commands: git push --delete git@cloud-10-0-0-38:liferay/liferay-portal cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git push -f git@cloud-10-0-0-39:liferay/liferay-portal.git master-temp-1698097669059:cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-1698097780096
 [parallel] Executing commands: git rev-parse master
 [parallel] Executing commands: git push -f git@cloud-10-0-0-34:liferay/liferay-portal.git master:master
 [parallel] Deleted git@cloud-10-0-0-36:liferay/liferay-portal branches:
 [parallel]     cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git branch | grep [\s\*]*master\$
 [parallel] Executing commands: git push -f git@cloud-10-0-0-35:liferay/liferay-portal.git master:master
 [parallel] Executing commands: git push -f git@cloud-10-0-0-33:liferay/liferay-portal.git master:master
 [parallel] Deleted git@cloud-10-0-0-37:liferay/liferay-portal branches:
 [parallel]     cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git branch | grep [\s\*]*master\$
 [parallel] Executing commands: git rev-parse master
 [parallel] Executing commands: git push --delete git@cloud-10-0-0-39:liferay/liferay-portal cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Deleted git@cloud-10-0-0-38:liferay/liferay-portal branches:
 [parallel]     cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git branch | grep [\s\*]*master\$
 [parallel] Executing commands: git rev-parse master
 [parallel] Executing commands: git push -f git@github-dev.cluster-2.lax.liferay.com:liferay/liferay-portal.git master-temp-1698097669059:cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git push -f git@github-dev.cluster-3.lax.liferay.com:liferay/liferay-portal.git master-temp-1698097669059:cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git push -f git@github-dev.cluster-4.lax.liferay.com:liferay/liferay-portal.git master-temp-1698097669059:cache-liferay-eea775f659698232bec1fa5eb34ad634669ee4ba-gamerson-fe5ec45feb037a24c393b91cc2afbaae95211f29-LOCK
 [parallel] Executing commands: git push -f git@cloud-10-0-0-36:liferay/liferay-portal.git master:master
 [parallel] Executing commands: git rev-parse master
 [parallel]   [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
 [parallel]   [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
 [parallel] Executing commands: git push -f git@cloud-10-0-0-37:liferay/liferay- [...]

2023-11-01 18:43 UTC, drewbrokke requested changes

2023-11-01 18:43 UTC, drewbrokke commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/ClientExtensionsSamples.testcase
> +			var found = false;
I think this has to be a string `"false"`, then the later comparison will look like:
```
if (${found} != "true") {
}
```

2023-11-09 15:01 UTC, drewbrokke commented
See https://github.com/drewbrokke/liferay-portal/pull/1561

2023-11-09 15:01 UTC, closed without merging