LPS-198875 upgrade plexus-utils version 3.0.24
drewbrokke/liferay-portal pull request #1538
Opened 2023-10-24 04:26 UTC by simonjhy

2023-10-24 04:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-24 14:10 UTC, drewbrokke requested changes
@simonjhy just one issue, please see my inline comment. There is another pull that already updated the soy dependency version here: https://github.com/brianchandotcom/liferay-portal/pull/142393. Let's just update the plexus dependency in this pull.

Thanks!

2023-10-24 14:10 UTC, drewbrokke commented on modules/util/portal-tools-soy-builder/build.gradle
> -	api group: "com.google.template", name: "soy", version: "2019-03-07"
Is the update to the `soy` dependency necessary for this update? If not, let's leave it off.

2023-10-24 21:50 UTC, drewbrokke commented
@simonjhy @Seiphon looks like there is overlapping work between this pull and https://github.com/drewbrokke/liferay-portal/pull/1536. Can you two coordinate and re-send? Thanks!

2023-10-24 21:50 UTC, closed without merging

2023-10-25 11:15 UTC, Seiphon commented
resent ther pr here https://github.com/drewbrokke/liferay-portal/pull/1541